// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

#include "unixasmmacros.inc"

NESTED_ENTRY ResolveWorkerAsmStub, _TEXT, NoHandler
// NOT YET IMPLEMENTED
.long 0x91
NESTED_END ResolveWorkerAsmStub, _TEXT

LEAF_ENTRY ResolveWorkerChainLookupAsmStub, _TEXT
// NOT YET IMPLEMENTED
.long 0x92
LEAF_END ResolveWorkerChainLookupAsmStub, _TEXT

